apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: KAFKA_UI_CFG_PATH
          value: /config/application.yml
      volumes:
      - name: config-volume
        configMap:
          name: kafka-ui-config

