apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: weather
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3 # parallel processing. improve scalability.
  replicas: 1 # redundancy. improve availability.
