include:
- ./functions/elasticSeach_insert_weather/insertWeatherIntoElasticSearch.py
- ./functions/elasticSeach_insert_weather/build.sh
- ./functions/elasticSeach_insert_weather/requirements.txt
kind: ArchiveUploadSpec
name: functions-elasticseach-insert-weather-insertweatherintoelastics-qfft

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: insert-weather-package
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-elasticseach-insert-weather-insertweatherintoelastics-qfft
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T13:10:50Z"
