include:
- functions/tharvester/tharvester.py
kind: ArchiveUploadSpec
name: functions-tharvester-tharvester-py-kxbq

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: tharvester-fa85651e-91fa-456a-970b-c34ec1effde7
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-tharvester-tharvester-py-kxbq
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-12T12:55:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: tharvester
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: tharvester-fa85651e-91fa-456a-970b-c34ec1effde7
      namespace: ""
  requestsPerPod: 1
  resources: {}
