include:
- functions/addobservations.zip
kind: ArchiveUploadSpec
name: functions-addobservations-zip-SKXL

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addobservations
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-addobservations-zip-SKXL
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T09:22:50Z"
