include:
- functions/wharvester.zip
kind: ArchiveUploadSpec
name: functions-wharvester-zip-yvyA

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-wharvester-zip-yvyA
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T03:29:11Z"
