include:
- ./functions/wharvester/wharvester.py
- ./functions/wharvester/requirements.txt
- ./functions/wharvester/build.sh
kind: ArchiveUploadSpec
name: functions-wharvester-wharvester-py-NyBr

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-wharvester-wharvester-py-NyBr
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:12:29Z"
