apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: enqueue
spec:
  createingress: false
  functionref:
    functionweights: null
    name: enqueue
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enqueue/{topic}
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /enqueue/{topic}
